name: aquasense
description: "Smart Water Supply and Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1

  # Firebase Core
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  firebase_app_check: ^0.3.0

  # Social Login & Security
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3

  # Utility
  dropdown_search: ^5.0.6
  intl_phone_field: ^3.2.0
  # NEW: Added for storing first-time launch status
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Register assets with correct directory paths
  assets:
    - assets/animations/
    - assets/icons/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"