// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhMFCOb6g5KIDsU28HOXw6BwBe48TJ3c',
    appId: '1:575158481229:web:06e1f8bfbf680d96e10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    authDomain: 'aquasense-e6f48.firebaseapp.com',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
    measurementId: 'G-NHPXZ1J5E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtz0CSuqcO52DULMGLq3dRw1zF5l6s7rs',
    appId: '1:575158481229:android:45382e4e1a403269e10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVg_qJLUbXzCkHZzBzq6dPHEc_ctDuV0',
    appId: '1:575158481229:ios:14bb89f0247ec4dde10704',
    messagingSenderId: '575158481229',
    projectId: 'aquasense-e6f48',
    storageBucket: 'aquasense-e6f48.firebasestorage.app',
    androidClientId: '575158481229-08hkdk440nkvm90ql6mir5bfipb0454c.apps.googleusercontent.com',
    iosClientId: '575158481229-6ag09ab2ojng9niap60b8vrno04tc0mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasense',
  );

}